# 网站基础信息
title: "record space"
description: "record"
author: "77777"

lang: zh-CN
timezone: Asia/Shanghai

# 主题设置 (关键部分)
remote_theme: pages-themes/hacker@v0.2.0

# remote_theme: cotes2020/jekyll-theme-chirpy@v5.6.0

# 插件开启
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# # 分页配置（必须开启，首页才能显示文章列表）
# paginate: 10
# paginate_path: /page:num/

url: "https://alivk353.github.io/"

# 5. 文章路径设置
# permalink: /posts/:title/

# # 尝试全局禁用侧边栏布局
# layout: page
# hide_sidebar: true

# theme_mode: dark # [light | dark]