
# SEO settings
title: "Think"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://nanazeven.github.io # site url
baseurl: "http://nanazeven.github.io" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/nanazeven/nanazeven.github.io
disqus_shortname: "***"
twitter_username: "***"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "NANAZEVEN"
  job      : "Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : qiyakun353@gmail.com
  url      : https://nanazeven.github.io
  github   : https://nanazeven.github.io
  twitter  : https://nanazeven.github.io
  facebook : https://nanazeven.github.io
  linkedin : https://nanazeven.github.io

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
