
# SEO settings
title: "0x07"
title2: "" # default: ""
description: "nana"
keywords: "github pages"
url: http://nanazeven.github.io # site url
baseurl: " " # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/nanazeven/nanazeven.github.io
disqus_shortname: "***"
twitter_username: "***"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "0x07"
  job      : " "
  bio      : "你将会成为你曾经看不起的那种人，这很痛苦"
  thumb    : /images/author.jpg
  email    : qiyakun353@gmail.com
  url      : https://nanazeven.github.io
  github   : https://nanazeven.github.io
  twitter  : https://nanazeven.github.io
  facebook : https://nanazeven.github.io
  linkedin : https://nanazeven.github.io

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

theme: jekyll-theme-cayman